// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /scratch_local/akalinow/CMS/OverlapTrackFinder/CMSSW_6_2_0_pre7/src/UserCode/L1RpcTriggerAnalysis/macros/plots/./utilsHistoFromGraph.h;
#pragma link C++ defined_in "/scratch_local/akalinow/CMS/OverlapTrackFinder/CMSSW_6_2_0_pre7/src/UserCode/L1RpcTriggerAnalysis/macros/plots/./utilsHistoFromGraph.C";

#endif
