//
// File generated by /usr/local/root_v5.34.07/bin/rootcint at Wed Jun 26 11:43:33 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dIscratch_localdIakalinowdICMSdIOverlapTrackFinderdICMSSW_6_2_0_pre7dIsrcdIUserCodedIL1RpcTriggerAnalysisdImacrosdIplotsdIutilsHistoFromGraph_C_ACLiC_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "utilsHistoFromGraph_C_ACLiC_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

/********************************************************
* /scratch_local/akalinow/CMS/OverlapTrackFinder/CMSSW_6_2_0_pre7/src/UserCode/L1RpcTriggerAnalysis/macros/plots/utilsHistoFromGraph_C_ACLiC_dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableutilsHistoFromGraph_C_ACLiC_dict();

extern "C" void G__set_cpp_environmentutilsHistoFromGraph_C_ACLiC_dict() {
  G__cpp_reset_tagtableutilsHistoFromGraph_C_ACLiC_dict();
}
#include <new>
extern "C" int G__cpp_dllrevutilsHistoFromGraph_C_ACLiC_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Setting up global function */
static int G__utilsHistoFromGraph_C_ACLiC_dict__0_1398(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TH1D* pobj;
         TH1D xobj = runHistoFromGraph((TGraph*) G__int(libp->para[0]));
         pobj = new TH1D(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__utilsHistoFromGraph_C_ACLiC_dict__0_1399(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      fillHistoFromGraph(*(TH1D*) libp->para[0].ref, (TGraph*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__utilsHistoFromGraph_C_ACLiC_dict__0_1400(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) getPressVsRunHisto((TH1D*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__utilsHistoFromGraph_C_ACLiC_dict__0_1401(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) getHumidityVsRunHisto((TH1D*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__utilsHistoFromGraph_C_ACLiC_dict__0_1402(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) getClusterSizeVsRunHisto((TH1D*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__utilsHistoFromGraph_C_ACLiC_dict__0_1403(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      printRunsOnPlotLinScale((TH1D*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__utilsHistoFromGraph_C_ACLiC_dict__0_1404(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      printRunsOnPlot((TH1D*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/*********************************************************
* Member function Stub
*********************************************************/

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncutilsHistoFromGraph_C_ACLiC_dict {
 public:
  G__Sizep2memfuncutilsHistoFromGraph_C_ACLiC_dict(): p(&G__Sizep2memfuncutilsHistoFromGraph_C_ACLiC_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncutilsHistoFromGraph_C_ACLiC_dict::*p)();
};

size_t G__get_sizep2memfuncutilsHistoFromGraph_C_ACLiC_dict()
{
  G__Sizep2memfuncutilsHistoFromGraph_C_ACLiC_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceutilsHistoFromGraph_C_ACLiC_dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableutilsHistoFromGraph_C_ACLiC_dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */
extern "C" void G__cpp_setup_memvarutilsHistoFromGraph_C_ACLiC_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/

/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncutilsHistoFromGraph_C_ACLiC_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalutilsHistoFromGraph_C_ACLiC_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
   G__memfunc_setup("runHistoFromGraph", 1762, G__utilsHistoFromGraph_C_ACLiC_dict__0_1398, 117, G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_TH1D), -1, 0, 1, 1, 1, 0, "U 'TGraph' - 10 - gr", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("fillHistoFromGraph", 1844, G__utilsHistoFromGraph_C_ACLiC_dict__0_1399, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TH1D' - 1 - histo U 'TGraph' - 0 - graph", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("getPressVsRunHisto", 1874, G__utilsHistoFromGraph_C_ACLiC_dict__0_1400, 85, G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_TH1D), -1, 0, 1, 1, 1, 0, "U 'TH1D' - 0 - histo", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("getHumidityVsRunHisto", 2194, G__utilsHistoFromGraph_C_ACLiC_dict__0_1401, 85, G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_TH1D), -1, 0, 1, 1, 1, 0, "U 'TH1D' - 0 - histo", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("getClusterSizeVsRunHisto", 2498, G__utilsHistoFromGraph_C_ACLiC_dict__0_1402, 85, G__get_linked_tagnum(&G__utilsHistoFromGraph_C_ACLiC_dictLN_TH1D), -1, 0, 2, 1, 1, 0, 
"U 'TH1D' - 0 - histo C - - 10 - fname", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("printRunsOnPlotLinScale", 2364, G__utilsHistoFromGraph_C_ACLiC_dict__0_1403, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TH1D' - 0 - histo", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("printRunsOnPlot", 1585, G__utilsHistoFromGraph_C_ACLiC_dict__0_1404, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TH1D' - 0 - histo", (char*) NULL
, (void*) NULL, 0);
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcutilsHistoFromGraph_C_ACLiC_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_TGraph = { "TGraph" , 99 , -1 };
G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableutilsHistoFromGraph_C_ACLiC_dict() {
  G__utilsHistoFromGraph_C_ACLiC_dictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__utilsHistoFromGraph_C_ACLiC_dictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__utilsHistoFromGraph_C_ACLiC_dictLN_TGraph.tagnum = -1 ;
  G__utilsHistoFromGraph_C_ACLiC_dictLN_TH1D.tagnum = -1 ;
  G__utilsHistoFromGraph_C_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__utilsHistoFromGraph_C_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__utilsHistoFromGraph_C_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__utilsHistoFromGraph_C_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__utilsHistoFromGraph_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableutilsHistoFromGraph_C_ACLiC_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__utilsHistoFromGraph_C_ACLiC_dictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__utilsHistoFromGraph_C_ACLiC_dictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__utilsHistoFromGraph_C_ACLiC_dictLN_TGraph);
   G__get_linked_tagnum_fwd(&G__utilsHistoFromGraph_C_ACLiC_dictLN_TH1D);
   G__get_linked_tagnum_fwd(&G__utilsHistoFromGraph_C_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__utilsHistoFromGraph_C_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__utilsHistoFromGraph_C_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__utilsHistoFromGraph_C_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__utilsHistoFromGraph_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
}
extern "C" void G__cpp_setuputilsHistoFromGraph_C_ACLiC_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setuputilsHistoFromGraph_C_ACLiC_dict()");
  G__set_cpp_environmentutilsHistoFromGraph_C_ACLiC_dict();
  G__cpp_setup_tagtableutilsHistoFromGraph_C_ACLiC_dict();

  G__cpp_setup_inheritanceutilsHistoFromGraph_C_ACLiC_dict();

  G__cpp_setup_typetableutilsHistoFromGraph_C_ACLiC_dict();

  G__cpp_setup_memvarutilsHistoFromGraph_C_ACLiC_dict();

  G__cpp_setup_memfuncutilsHistoFromGraph_C_ACLiC_dict();
  G__cpp_setup_globalutilsHistoFromGraph_C_ACLiC_dict();
  G__cpp_setup_funcutilsHistoFromGraph_C_ACLiC_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncutilsHistoFromGraph_C_ACLiC_dict();
  return;
}
class G__cpp_setup_initutilsHistoFromGraph_C_ACLiC_dict {
  public:
    G__cpp_setup_initutilsHistoFromGraph_C_ACLiC_dict() { G__add_setup_func("utilsHistoFromGraph_C_ACLiC_dict",(G__incsetup)(&G__cpp_setuputilsHistoFromGraph_C_ACLiC_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initutilsHistoFromGraph_C_ACLiC_dict() { G__remove_setup_func("utilsHistoFromGraph_C_ACLiC_dict"); }
};
G__cpp_setup_initutilsHistoFromGraph_C_ACLiC_dict G__cpp_setup_initializerutilsHistoFromGraph_C_ACLiC_dict;

