/********************************************************************
* /scratch_local/akalinow/CMS/OverlapTrackFinder/CMSSW_6_2_0_pre7/src/UserCode/L1RpcTriggerAnalysis/macros/plots/utilsHistoFromGraph_C_ACLiC_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /scratch_local/akalinow/CMS/OverlapTrackFinder/CMSSW_6_2_0_pre7/src/UserCode/L1RpcTriggerAnalysis/macros/plots/utilsHistoFromGraph_C_ACLiC_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableutilsHistoFromGraph_C_ACLiC_dict();
extern void G__cpp_setup_inheritanceutilsHistoFromGraph_C_ACLiC_dict();
extern void G__cpp_setup_typetableutilsHistoFromGraph_C_ACLiC_dict();
extern void G__cpp_setup_memvarutilsHistoFromGraph_C_ACLiC_dict();
extern void G__cpp_setup_globalutilsHistoFromGraph_C_ACLiC_dict();
extern void G__cpp_setup_memfuncutilsHistoFromGraph_C_ACLiC_dict();
extern void G__cpp_setup_funcutilsHistoFromGraph_C_ACLiC_dict();
extern void G__set_cpp_environmentutilsHistoFromGraph_C_ACLiC_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/scratch_local/akalinow/CMS/OverlapTrackFinder/CMSSW_6_2_0_pre7/src/UserCode/L1RpcTriggerAnalysis/macros/plots/./utilsHistoFromGraph.C"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_TGraph;
extern G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_TH1D;
extern G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__utilsHistoFromGraph_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;

/* STUB derived class for protected member access */
