/********************************************************************
* rootMAnaDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootMAnaDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablerootMAnaDict();
extern void G__cpp_setup_inheritancerootMAnaDict();
extern void G__cpp_setup_typetablerootMAnaDict();
extern void G__cpp_setup_memvarrootMAnaDict();
extern void G__cpp_setup_globalrootMAnaDict();
extern void G__cpp_setup_memfuncrootMAnaDict();
extern void G__cpp_setup_funcrootMAnaDict();
extern void G__set_cpp_environmentrootMAnaDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "UserCode/L1RpcTriggerAnalysis/interface/EventObj.h"
#include "UserCode/L1RpcTriggerAnalysis/interface/L1Obj.h"
#include "UserCode/L1RpcTriggerAnalysis/interface/L1ObjColl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__rootMAnaDictLN_TClass;
extern G__linked_taginfo G__rootMAnaDictLN_TBuffer;
extern G__linked_taginfo G__rootMAnaDictLN_TMemberInspector;
extern G__linked_taginfo G__rootMAnaDictLN_TObject;
extern G__linked_taginfo G__rootMAnaDictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__rootMAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__rootMAnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootMAnaDictLN_EventObj;
extern G__linked_taginfo G__rootMAnaDictLN_L1Obj;
extern G__linked_taginfo G__rootMAnaDictLN_L1ObjColl;
extern G__linked_taginfo G__rootMAnaDictLN_vectorlEL1ObjcOallocatorlEL1ObjgRsPgR;
extern G__linked_taginfo G__rootMAnaDictLN_reverse_iteratorlEvectorlEL1ObjcOallocatorlEL1ObjgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
